version: '3'

services:
  app:
    build: .
    container_name: testAPI
    network_mode: host
    ports:
      - "8000:8000"
    command: uvicorn app.main:app
    env_file:
      - .env
    volumes:
      - ./testAPI.db:/app/testAPI.db:delegated
